version: '3'
services:
  app:
    build: ./client/
    restart: always
    image: sistema-scolare_app
    expose:
      - 80
    environment:
      VIRTUAL_HOST: ${NGINX_DOMAIN}
      LETSENCRYPT_HOST: ${NGINX_DOMAIN}
      LETSENCRYPT_EMAIL: ${NGINX_EMAIL}
    
  storybook:
    build:
      context: ./client/
      dockerfile: Dockerfile-storybook
    restart: always
    image: sistema-scolare_storybook
    expose:
      - 2001
    environment:
      API_HOST: ${NGINX_DOMAIN}
      API_PORTS: 2001
  
  mysql-development:
    image: mysql:5.7
    restart: always
    volumes:
      - ./server/scripts/import:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: app
    ports:
      - "3308:3306"
  
  server:
    build: ./server/
    restart: always
    image: sistema-scolare_server
    depends_on:
      - mysql-development
    expose:
      - 3001
    volumes:
      - certs:/etc/nginx/certs:ro
    environment:
      API_HOST: ${NGINX_DOMAIN}
      API_PORTS: 3001
      API_HTTPS: 3001

networks:
    default:
        external:
            name: nginx-proxy

volumes:
  certs:
    external:
      name:  nginx-proxy_certs
            
